from django.test import TestCase
from datetime import datetime, date
# Create your tests here.

skill_list = [
    "Abstract Factory",
    "Accounting System",
    "Accuracy and Precision",
    "Acquisition management",
    "ActiveRecord",
    "Acunetix",
    "Acute Coronary Syndrome",
    "Acute Pain Management",
    "ADamSoft",
    "ADIC",
    "Administration and Configuration",
    "Adobe Fireworks",
    "Adobe FrameMaker",
    "Adobe FreeHand",
    "Adolescent Health",
    "Advanced Features of Carbonado",
    "Aggressive Marketing",
    "Agile",
    "AgileJ StructureViews",
    "Agm",
    "AhnLab Site Guard",
    "AIML",
    "AlaSQL",
    "Aleph",
    "All-Source Analysis",
    "Alternative Dispute Resolution",
    "ALV Reporting",
    "Amanda",
    "Amateur Photography",
    "Amazon SQS",
    "AMD Am29000",
    "Amira",
    "AMPL",
    "AMQP",
    "Anaerobic Microbiology",
    "Analog Multimeter",
    "Analyse-it",
    "Animal and Stem Cells",
    "Annuity",
    "AnyDoc Software",
    "Apache Mina SSHD",
    "API Testing",
    "Apollo",
    "Apple Graphics Library ",
    "Apple Motion",
    "Applied to Discrete Models",
    "Aquatic Therapy",
    "Arabic",
    "Arbortext Command",
    "Ardor3D",
    "Arduino Diecimila",
    "ArgoUML",
    "Arranging Angel Funding",
    "Arts Integration",
    "ASC-THCLSO11",
    "Asian Cuisine",
    "ASP.NET",
    "ASRemi",
    "Asset Write Downs",
    "Astah",
    "Athletic Footwear",
    "ATL",
    "Autodesk Inventor",
    "Automated Testing",
    "Automotive Industry Knowledge",
    "Availability Management",
    "Awk Programming Language",
    "B.Tech",
    "BABOK",
    "Bachman",
    "Back Bay",
    "BackBox",
    "Backjumping",
    "Bacterio",
    "Badboy",
    "Balochi",
    "Bancware",
    "Behavior Management",
    "Belief Propagation",
    "Bell Desk",
    "Bi-Directional RNN",
    "Biochip",
    "Bitvise SSH Server",
    "BizTalk",
    "Black-Box Testing",
    "BOOPSI",
    "Bottle",
    "British Standards",
    "Bulk Endocytosis",
    "Burp Suite",
    "Business Consultant",
    "Business Studies",
    "Butchery",
    "C Programming Language",
    "C Suite",
    "C#",
    "Cakewalk",
    "Call Logging",
    "Capacity Management",
    "Capacity Management Strategies",
    "Carbon Credits",
    "Cartels",
    "Cash Advance",
    "Cash Management",
    "Catalog Merchandising",
    "CBP-IEEE",
    "CCA - PegaSystems",
    "CDCP",
    "Ceramic Analysis",
    "Change Management",
    "Chipscope Pro",
    "Chlorin",
    "Chronic Rhinitis",
    "Circumscription Logic",
    "CisionPoint",
    "Clade",
    "ClickDummy",
    "Client Education",
    "Client Focus",
    "Client Relations",
    "CLM",
    "Cloud",
    "CLR Profiler",
    "Cobal",
    "Code Coverage Tools",
    "Codeship",
    "Cold Calls",
    "Collection",
    "Compatibility Testing",
    "Compiler Development",
    "Compiling",
    "Concert Photography",
    "Connector",
    "Consensus decision-making",
    "Contextual Design",
    "Convolutional Neural Network",
    "CopSSH",
    "Core Graphics",
    "CRB",
    "Create Test Strategy",
    "Critical Care Medicine",
    "CRM Sales",
    "Crop Protection",
    "C-TPAT",
    "Cupping",
    "Custom Synthesis",
    "CWP-ED",
    "CY8C5xxxx",
    "Cython",
    "D900",
    "DaDaBik",
    "Data Design System",
    "Data Dictionary",
    "Data Management",
    "Data Systems",
    "Database Capacity Management",
    "Database Creation",
    "Database Monitoring & Performance Tuning",
    "DataONE",
    "Dbx Debugger",
    "DDoS Mitigation",
    "Dealer Operations",
    "Debugging",
    "Defaunation",
    "Defining the Specification",
    "Dental Anesthesia",
    "Department Budgeting",
    "Deployment Management",
    "Design and Planning",
    "Desktop Application Development",
    "Development of Triggers",
    "Dielectric Heating",
    "Digital Imaging",
    "DirSync Pro",
    "Disaster Mitigation",
    "Discourse Analysis",
    "Discrete Phase-Type Distribution",
    "Diversity Recruitment",
    "Dividend Yield",
    "Do",
    "Dropmysite",
    "DSDM",
    "Dynamics NAV Server",
    "Eager Learning",
    "Easy CD Creator",
    "Eclipse TPTP",
    "Eco-efficiency",
    "Eco-Investing",
    "EDA",
    "EDRP",
    "EDWinXP",
    "Ejector Refrigeration Systems",
    "ElephantDrive",
    "Embedded Systems",
    "Encore",
    "Encryption Software",
    "EnergyMech",
    "Engagement Marketing",
    "Enteral Feeding",
    "Enterprise Application Development",
    "Entrepreneurial Finance",
    "Environmental Data Analysis",
    "Environmental Geology",
    "EOS",
    "EPMA",
    "EPMLive",
    "EQATEC Profiler",
    "ERP Selection",
    "Escalations",
    "ESpeak",
    "Eukaryotic Initiation Factor",
    "European Politics",
    "Evolutionary Art",
    "Facility management",
    "FactSet",
    "Family Medicine",
    "Fantom",
    "FAQ",
    "FDMA",
    "FedEx",
    "Feeder Protection",
    "FEMA Matters",
    "File Commander",
    "Files-11",
    "Financial Freedom",
    "Financial Sector",
    "Finite-Difference Time-Domain Method",
    "Fire Pumps",
    "Firmware",
    "Fluke",
    "FMOD",
    "FOH",
    "Folkewall",
    "Follow-on Offerings",
    "Forensic Anthropology",
    "fortrabbit",
    "Front End Programming/Scripting",
    "FSG",
    "FTA",
    "Functional Viewpoint",
    "Fund Flow Statement",
    "Futures",
    "G8D",
    "Galaxkey",
    "Gallery Administration",
    "Game Artificial Intelligence",
    "Game Development",
    "Games, Entertainment",
    "GD Graphics Library",
    "Gene Silencing",
    "General Accounts",
    "Generating Primary Keys",
    "Generating Revenue",
    "Generative Topographic Map",
    "Genomic Counseling",
    "Genomic Imprinting",
    "GLIMMERHMM",
    "Global",
    "Global Label Management",
    "Global Strategy",
    "GlowCode",
    "GNU M4",
    "GNU Toolchain",
    "Go",
    "Google BigQuery",
    "Government Relations",
    "Gradle",
    "Grant management",
    "Granular Configuration Automation",
    "Group Policy",
    "gulp.js",
    "Gypsum",
    "Hadoop",
    "Hair Stylist",
    "Ham Passwords",
    "Hammond Organ",
    "HAP",
    "Hardware Sizing",
    "Hbase",
    "HCFA",
    "HCNP-CC",
    "Health Club",
    "Healthcare Consulting",
    "Healthcare Transaction base",
    "HEC-2",
    "Here",
    "Hilbert System",
    "Home Warranty",
    "Homebuilding",
    "HORNETDRIVE",
    "Hospital Pharmacy",
    "Hospitals, Clinics",
    "HP StorageWorks",
    "HR Coordination",
    "HR Software",
    "Huffyuv",
    "IMAGE cDNA Clones",
    "Immigration",
    "IMS DB",
    "Infographics",
    "Informatica PowerCenter",
    "Injectable",
    "Ink Cartridges",
    "Insurance Advisory",
    "Insurance Bank",
    "Integrated Design",
    "Interactomics",
    "International Real Estate",
    "International Regulations",
    "Inverse Dynamics",
    "IoT Operating System",
    "IPSec",
    "ISO Procedures",
    "ISO/TS 16949",
    "Iterative Viterbi Decoding",
    "IwGame Engine",
    "Job Coaching",
    "Juvederm",
    "JZBot",
    "Keen Planner",
    "Kimball Methodology",
    "Kreata Global",
    "KYC",
    "Labour Laws",
    "Lamebook",
    "LANDesk management",
    "Language Services",
    "Laser beam",
    "Lattice C",
    "Layouting",
    "LEED",
    "Legal Process",
    "Libpolo",
    "Licensed Master Electrician",
    "Life/work Balance",
    "LifeSize Video Conferencing",
    "Lightwave",
    "Link Contract",
    "Linode",
    "Linux Userland File System",
    "LINX (IPC)",
    "Liquid Handling Robot",
    "LiquidPlanner",
    "LIS",
    "LisaProject",
    "Literary Theory",
    "Live Event Producer",
    "Livestock Husbandary",
    "Load Runner 7.x",
    "Long Hair",
    "LPR",
    "LSF",
    "LTE Physical Layer",
    "Lymphoid Organs",
    "Machine Learning",
    "Macintosh Networking",
    "MacProject",
    "Madaline",
    "Magento Architecture",
    "Magics",
    "Mailers",
    "Major Gift Solicitations",
    "Making Deposits",
    "Mallet Software Project",
    "Management of Suppliers",
    "Managing Database Instances",
    "Manpower Utilization",
    "Mantis",
    "MASE-NSSysSup07",
    "Master Scheduling",
    "MBE",
    "McCLIM",
    "MCITP(GP 10.0)",
    "Medical Compliance",
    "Medical Practice",
    "Medication Administration",
    "Mentoring New Hires",
    "Meta Databases",
    "Microeconomics",
    "Microsoft Exchange",
    "Microsoft Intermediate",
    "Microsoft PIX",
    "Microsoft Software Updater",
    "Microsoft Windows administration",
    "Microsoft Yammer",
    "MiniGLX",
    "MMDF",
    "MOAB",
    "Mobile Application",
    "mod jk",
    "ModelRight",
    "Modems",
    "Modernization",
    "Molecular Biology",
    "Molecular Genetics",
    "monkeyrunner",
    "MONOCLdb",
    "MoU",
    "Moulds",
    "MPC-MLQ",
    "MS Cluster",
    "MS SQL Server",
    "MSP Advanced Practitioner",
    "Multi-country",
    "Multimedia Bandwidth",
    "Multiservice Media Gateway",
    "Music Criticism",
    "Music Journalism",
    "MySAP CRM",
    "NAMD",
    "Namespace Nodes",
    "Nautilus",
    "NCBI Epigenomics",
    "Nearshore",
    "Netsniff-ng",
    "Network enhancements",
    "NeXpose",
    "Nielsen Nitro",
    "NIH Shift",
    "Node.js Stream",
    "Nokia IPSO",
    "Non-infringement",
    "Novell Netmail",
    "Nuitka",
    "Numerical Simulation",
    "Obfuscation",
    "Objective C",
    "OBPM",
    "ODE",
    "Olympic Lifting",
    "Oncology",
    "Opening Hotels",
    "OpenOffice",
    "OpenSMTPD",
    "Operational Execution",
    "Ophthalmics",
    "Oracle Data Mining",
    "Organization Performance Management",
    "Pacemaker",
    "Package Inserts",
    "PADS",
    "Panchakarma",
    "Paper Converting",
    "Parent-Teacher Communication",
    "PASMA",
    "Passive House",
    "Password management",
    "Password Protection",
    "Payroll Taxes",
    "PEGylation",
    "Personal Accident",
    "Pharmaceutical Production",
    "PhotoModeler",
    "PicOS",
    "PicTar",
    "Pioneer Factor",
    "Piping Isometrics",
    "PL/1",
    "Plant Layout Preparation",
    "Plasma Cutting",
    "Plasmas",
    "Platial",
    "PLC M",
    "Pneumonia",
    "Podcast Submissions",
    "Political Participation",
    "Polypropylene",
    "Poseidon for UML",
    "PostGIS",
    "POSTMAN",
    "Pre-Boot Authentication",
    "Predictive Learning",
    "Preparation",
    "Primary Biliary Cirrhosis",
    "Primer Design",
    "Print Marketing",
    "Process Scheduler",
    "Product Analysis",
    "Production Budgeting",
    "Professional Ethics",
    "Professional Negligence",
    "Profitability Manager",
    "Programmers",
    "Programming for",
    "Project Initiation",
    "Project Purchasing",
    "Prolog",
    "ProRealTime",
    "Protein Expression",
    "Psychological Assessment",
    "Psychosocial",
    "Python Class Mechanism",
    "Pyxplot",
    "Q.SIG",
    "Quality Assurance Professionals",
    "Quality Auditing",
    "Quality Center",
    "Quality Control Tools",
    "RAC Administration",
    "Raku",
    "Real Estate Financing",
    "Reason 5",
    "Recover My Files",
    "Remediation Engineering",
    "Reporting",
    "Rescue Diving",
    "Respiratory Quotient",
    "Reunion",
    "Reverse Osmosis Plants",
    "Revolving Lines of Credit",
    "Rhetoric",
    "Ribosomal Binding Site",
    "RISC Architecture",
    "RNA Editing",
    "RNAstructure",
    "Robotics Hardware",
    "Role Model",
    "ROOT Statistical Software",
    "RTI",
    "RuBot II",
    "Rural Health",
    "Safety Culture",
    "SAG",
    "SAIL",
    "Sales Brochures",
    "Sandwiches",
    "SAP CRM 7.0",
    "SAP EC",
    "SAP EHS",
    "SAP EP",
    "SAP EWM",
    "SAP FM",
    "SAP FSCM",
    "Sar (Unix)",
    "SAS Macros",
    "SAS/C C++",
    "Scandinavian",
    "Schaefer Dichotomy Theorem",
    "Scheme - Strings",
    "Scholarly Communication",
    "Scratch Golfer",
    "Scripting",
    "Search & Rescue",
    "Selenium IDE",
    "Sell Side",
    "Sellerdeck",
    "Semantria",
    "Sequential Erlang Programming",
    "Sequential Pattern Mining",
    "Servant",
    "Set Construction",
    "Shaft Alignment",
    "SHARC",
    "Shareplex",
    "Shortage Control",
    "Sieve Analysis",
    "Silk Test",
    "Silverstripe",
    "SimGear",
    "Similarity Learning",
    "Sintering",
    "Sirius",
    "Site Acquisition",
    "Site Maps",
    "Six Sigma Initiatives",
    "Slang",
    "S-Lang Programming Library",
    "Smalltalk Compilers",
    "Smart View",
    "Software Project Management",
    "Solarwinds SIEM",
    "Solid Surface",
    "Sony Vegas Video",
    "Soprano",
    "Source Code Control System",
    "Spot Model Checker",
    "SPV",
    "Spyder",
    "SQL Commands",
    "Stage Setting",
    "Stamp Duties",
    "Start-up Environment",
    "Start-up Support",
    "State Space Planning",
    "Statistical semantics",
    "Stellent",
    "Stones",
    "Storage engineering",
    "Story Editing",
    "Strata 3D",
    "Strategic Visionary",
    "Studio",
    "Sub7",
    "Subcontractor/Crew Supervision",
    "Subfunctionalization",
    "SuiteCRM",
    "Sulfonamides",
    "SuperMap",
    "Surgical Pathology",
    "SVOX",
    "System documentation",
    "System Identification",
    "Systems Ecology",
    "Tactics",
    "Talent Development",
    "TCP/IP",
    "Tcsh",
    "Team Operations",
    "TeamViewer",
    "Techinline",
    "Temperature",
    "Teradici",
    "Test Case Design",
    "Test Development",
    "Test Point Analysis",
    "Testing for compatibility",
    "The Robotic Workshop",
    "Thermophilic Microbes",
    "ThinC",
    "Thyroid Surgery",
    "TIBCO Designer",
    "Tobacco Treatment",
    "Traffic channel operations",
    "Transcription Factors",
    "Travel Coordination",
    "Tree Testing",
    "Trimos",
    "Troubleshooting Skills",
    "Trustee",
    "Turf",
    "TXL",
    "UMTS",
    "Underground Mining",
    "Underscore.js",
    "Union Management",
    "Unix Korn Shell Scripting",
    "Upgrading Rails",
    "Varnish",
    "VBC",
    "Vendor Master Data Management",
    "Veraz",
    "VGACAD",
    "Visual",
    "Visual SourceSafe ",
    "Viz Artist",
    "V-Max",
    "VMGL",
    "VSD",
    "VSS",
    "Waste Water",
    "Water Resource Engineering",
    "WBTs",
    "Web API",
    "WebDrive",
    "Websocket.js",
    "WinSCP",
]


# for item in skill_list:
#     print("('{value1}','{value2}'),".format(value1=item,value2=item))



# def salary_computation(salary):
#     per_day = salary / 20
#     per_min = per_day / 510
#     thirty_min = per_min * 30
#     hour = per_min * 60
#     eight_hours = hour * 8
#     total_working_hourse = eight_hours + thirty_min

#     print('Salary:', salary)
#     print('Salary Per Min:',per_min)
#     print('Salary Per 30 mins:', thirty_min)
#     print('Salary Per Hour:',hour)
#     print('Salary for 8 hours:',eight_hours)
#     print('Total working hours a day:', total_working_hourse)


# salary_computation(salary=20000)

# s1 = '10:33'
# s2 = '11:15' # for example
# FMT = '%H:%M'
# tdelta = (datetime.strptime(s2, FMT) - datetime.strptime(s1, FMT) ).total_seconds()

# print(tdelta / 60)


def computation(monthly_rate):
    #Daily Rate = (Monthly Rate X 12) / Total working days in a year. 
    #Php 575.08 = (Php 15,000 X 12) / 313 if working Mondays to Saturdays 
    #Php 689.66 = (Php 15,000 X 12) / 261 if working Mondays to Fridays

    # For Monthly Paid employees  
    # Hourly rate = (Monthly Rate X 12) / total working days in a year/ total working hours per day 
    # Php 71.88 = (15,000 X 12) / 313 / 8

    # For Daily paid employees 
    # Hourly rate = (Daily rate/total working hours per day) 
    # Php 57.00 = (456.00/8)
    daily_rate = (monthly_rate * 12) / 313
    hourly_rate = daily_rate / 8
    min_rate = hourly_rate / 60

    print(round(daily_rate, 2))
    print(round(hourly_rate, 2))
    print(round(min_rate, 2))

# computation(20000)

# today = date.today()
#
# date_today = dt.strftime("%Y") 
# print(date_today)
Computing_Pay_for_Work_Done  = (
    ('Regular Day','Regular Day'),
    ('Special Day','Special Day'),
    ('Special Day and Rest Day','Special Day and Rest Day'),
    ('Regular Holiday','Regular Holiday'),
    ('Regular Holiday and Rest Day','Regular Holiday and Rest Day'),
    #('Night Shift Ordinary Day','Night Shift Ordinary Day'),
    #('Night Shift Rest Day, Special Day or Regular Holiday','Night Shift Rest Day, Special Day or Regular Holiday'),
    ('Vacation Leave','Vacation Leave'),
    ('Maternity Leave','Maternity Leave'), 
    ('Sick Leave','Sick Leave'),
    ('Paternity Leave','Paternity Leave'),
    ('Leave without pay','Leave without pay'),
    ('Others','Others'),
)

# print(Computing_Pay_for_Work_Done[0][0])



#https://stackabuse.com/converting-strings-to-datetime-in-python/
# import datetime

# date_time_str = '2018-06-29 08:15:27.243860'
# date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S.%f')

# print('Date:', date_time_obj.date())
# print('Time:', date_time_obj.time())
# print('Date-time:', date_time_obj)
# https://www.w3schools.com/python/python_datetime.asp

date_time_str = "2020-06-12"
date_time_obj = datetime.strptime(date_time_str, '%Y-%m-%d')
print('Converted:', date_time_obj.strftime('%b %d %Y'))

