from django.urls import path
from application import views

app_name = "application"

urlpatterns = [
    path('user/profile/', views.user_profile, name='user_profile'),
    path('user/new/profile/', views.new_profile, name='new_user_profile'),
    path('user/edit/profile/', views.edit_profile, name='edit_user_profile'),
    path('user/profile/image/', views.save_profile_image, name='save_profile_image'),
    path('user/profile/mobile_number/', views.add_mobile_number, name='add_mobile_number'),
    path('user/profile/mobile_number/delete/<int:id>/', views.delete_mobile_number, name='delete_mobile_number'),
    path('user/profile/skill/', views.add_skill, name='add_skill'),
    path('user/profile/skill/delete/<int:id>/', views.delete_skill, name='delete_skill'),
    path('user/new/company/details/', views.new_company_details, name='new_company_details'),
    path('user/edit/company/details/', views.edit_company_details, name='edit_company_details'),
    path('user/profile/telephone_number/', views.add_telephone_number, name='add_telephone_number'),
    path('user/profile/telephone_number/delete/<int:id>/', views.delete_telephone_number, name='delete_telephone_number'),
    path('attendance/cutoff/', views.cut_off_page, name="cut_off_page"),    
    path('employees/employee/list/', views.employee_list_page, name="employee_list"),
    path('employees/employee/list/payroll/settings/<str:key>/', views.employee_payroll_base_salary_settings, name="employee_payroll_settings"),
    path('employees/employee/delete/<int:id>/', views.delete_employee, name="delete_employee"),
    path('attendance/cutoff/upload/', views.upload_attendance, name="upload_attendance"),
    path('attendance/cutoff/delete/<int:id>/', views.delete_attendance, name="delete_attendance"),
    path('employees/attendance/view/<str:pk>/', views.employee_attendance, name="employee_attendance_view"),
    path('employees/attendance/view/cutoff/<str:pk>/<int:id>/', views.employee_attendance_cutoff, name="employee_attendance_cut_off_view"),
    path('employees/attendance/view/cutoff/manual/<str:pk>/<int:id>/', views.employee_attendance_manual_configuration, name="employee_attendance_cut_off_manual"),
    path('employees/payroll/manage/', views.employee_payroll_page, name="employee_payroll_manage"),
    path('employees/payroll/manage/cutoff/<int:id>/', views.employee_payroll_employee_list, name="employee_payroll_manage_employee_list"),
    path('employees/payroll/manage/cutoff/create/payroll/<str:key>/<int:id>/', views.employee_create_payroll, name="employee_create_payroll"),
    path('employees/payroll/manage/cutoff/edit/payroll/<str:key>/<int:id>/', views.employee_edit_payroll, name="employee_edit_payroll"),
    path('employees/payroll/manage/cutoff/delete/payroll/<str:key>/<int:id>/', views.employee_delete_payroll, name="employee_delete_payroll"),
    path('employees/manage/leaves/', views.employee_manage_leaves, name="employee_manage_leaves_page"),
    path('employees/manage/leaves/view/<int:id>/', views.employee_view_employee_leaves, name="employee_view_employee_leaves_page"),
    path('employees/manage/iteneraries/', views.employee_manage_itenerary, name="employee_manage_iteneraries_page"),
    path('employees/manage/iteneraries/view/<int:id>/', views.employee_view_itenerary, name="employee_view_iteneraries_page"),
    path('employees/manage/admin/concerns/', views.employee_manage_concerns, name="employee_manage_concerns_page"),
    path('employees/manage/admin/concerns/create/', views.employee_create_concern, name="employee_create_concerns_page"),
    path('employees/manage/admin/concerns/edit/<int:id>/', views.employee_edit_concern, name="employee_edit_concerns_page"),
    path('employees/manage/admin/concerns/view/<int:id>/', views.employee_view_concern, name="employee_view_concerns_page"),
    path('employees/manage/admin/concerns/delete/<int:id>/', views.employee_delete_concern , name="employee_delete_concerns_page"),
    path('employees/manage/admin/concerns/inbox/', views.employee_manage_inbox_concern, name="employee_manage_inbox_concerns_page"),
    path('employees/manage/admin/concerns/reply/<int:id>/', views.employee_reply_concern , name="employee_reply_concerns_page"),
    path('employees/manage/reports/', views.reports_page, name="employee_reports"),
    
    path('users/nofitications/manager/delete/<int:id>/', views.read_notifications, name="users_notifications_delete"),
    path('users/nofitications/manager/delete/all/', views.read_all_notifications, name="users_notifications_delete_all"),
    path('users/maintainancepage/',views.maintainance_page, name="users_maintainance_page"),


    #employee side
    path('employee/profile/', views.employee_profile, name='employee_profile'),
    path('employee/attendance/cutoffandpayroll/', views.side_employee_cut_off_payroll_page, name="employee_side_cutoff_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/attendance/<int:id>/', views.side_employee_cut_off_page, name="employee_side_cutoff_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/<int:id>/', views.side_employee_view_payroll_page, name="employee_side_view_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/print/<int:id>/', views.side_employee_print_payroll_page, name="employee_side_print_payroll_page"),
    path('employee/manage/leaves/', views.side_employee_manage_leaves_page, name="employee_side_manage_leaves_page"),
    path('employee/manage/leaves/create/', views.side_employee_create_leave_form, name="employee_side_create_leave_form"),
    path('employee/manage/leaves/edit/<int:id>/', views.side_employee_edit_leave_form, name="employee_side_edit_leave_form"),
    path('employee/manage/leaves/delete/<int:id>/', views.side_employee_delete_leave_form, name="employee_side_delete_leave_form"),
    path('employee/manage/leaves/view/<int:id>/', views.side_employee_view_leave_form, name="employee_side_view_leave_form"),
    path('employee/manage/iteneraries/', views.side_employee_manage_inteneraries, name="employee_side_manage_iteneraries_page"),
    path('employee/manage/iteneraries/create/', views.side_employee_create_inteneraries, name="employee_side_create_iteneraries_page"),
    path('employee/manage/iteneraries/edit/<int:id>/', views.side_employee_edit_inteneraries, name="employee_side_edit_iteneraries_page"),
    path('employee/manage/iteneraries/delete/<int:id>/', views.side_employee_delete_inteneraries, name="employee_side_delete_iteneraries_page"),
    path('employee/manage/iteneraries/view/<int:id>/', views.side_employee_view_itenerary_form, name="employee_side_view_iteneraries_page"),
    path('employee/manage/concerns/', views.side_employee_manage_concerns, name="employee_side_manage_concerns_page"),
    path('employee/manage/concerns/create/', views.side_employee_create_concern, name="employee_side_create_concerns_page"),
    path('employee/manage/concerns/edit/<int:id>/', views.side_employee_edit_concern, name="employee_side_edit_concerns_page"),
    path('employee/manage/concerns/delete/<int:id>/', views.side_employee_delete_concern, name="employee_side_delete_concerns_page"),
    path('employee/manage/concerns/view/<int:id>/', views.side_employee_view_concern, name="employee_side_view_concerns_page"),
    path('employee/manage/concerns/inbox/', views.side_employee_manage_inbox_concern, name="employee_side_manage_inbox_concerns_page"),
    path('employee/manage/concerns/reply/<int:id>/', views.side_employee_reply_concern, name="employee_side_reply_concerns_page"),
    path('employee/maintainancepage/', views.employee_side_maintainance_page, name="employee_side_maintainance_page"),
    
]