# Generated by Django 2.2.3 on 2020-02-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20200219_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneNumberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_telephone_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephone_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_skills_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_mobile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('sss_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pagibig', models.CharField(blank=True, max_length=50, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_company_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
