# Generated by Django 2.2.3 on 2020-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
