# Generated by Django 2.2.3 on 2020-03-24 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200226_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumberinfo',
            name='fk_mobile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillsinfo',
            name='fk_skills_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telephonenumberinfo',
            name='fk_telephone_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephone_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
