# Generated by Django 2.2.3 on 2020-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200324_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsinfo',
            old_name='skills_number',
            new_name='skills',
        ),
    ]
