# Generated by Django 2.2.3 on 2020-04-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200420_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
