# Generated by Django 2.2.3 on 2020-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200429_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
