# Generated by Django 2.2.3 on 2020-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200429_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
