# Generated by Django 2.2.3 on 2020-05-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_employeepayroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayroll',
            name='payroll_cutoff_period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_cutoff_fk', to='application.CutOffPeriodInfo'),
        ),
    ]
