# Generated by Django 2.2.3 on 2020-05-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_employeepayroll_thirteenth_month_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(default='None', max_length=30)),
                ('employee_salary_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_fk', to='application.PersonalInfo')),
            ],
        ),
    ]
