# Generated by Django 2.2.3 on 2020-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_employeesalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='None', max_length=150)),
                ('link', models.CharField(default='None', max_length=250)),
                ('is_seen', models.BooleanField(default=False)),
                ('date_triggered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='reason',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
