# Generated by Django 2.2.3 on 2020-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20200521_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceinfo',
            name='payment_computation_for_work_done',
            field=models.CharField(choices=[('Regular Day', 'Regular Day'), ('Special Day', 'Special Day'), ('Special Day and Rest Day', 'Special Day and Rest Day'), ('Regular Holiday', 'Regular Holiday'), ('Regular Holiday and Rest Day', 'Regular Holiday and Rest Day'), ('Night Shift Ordinary Day', 'Night Shift Ordinary Day'), ('Night Shift Rest Day, Special Day or Regular Holiday', 'Night Shift Rest Day, Special Day or Regular Holiday')], default=('Regular Day', 'Regular Day'), max_length=100),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='payment_computation_overtime',
            field=models.CharField(choices=[('Ordinary Days', 'Ordinary Days'), ('Rest Day, Special Day, or Regular Day', 'Rest Day, Special Day, or Regular Day'), ('Night Shift Ordinary Day', 'Night Shift Ordinary Day'), ('Night Shift Rest Day, Special Day or Regular Holiday', 'Night Shift Rest Day, Special Day or Regular Holiday')], default=('Ordinary Days', 'Ordinary Days'), max_length=100),
        ),
    ]
