# Generated by Django 2.2.3 on 2020-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20200525_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='payment_computation_for_work_done',
            field=models.CharField(choices=[('Regular Day', 'Regular Day'), ('Special Day', 'Special Day'), ('Special Day and Rest Day', 'Special Day and Rest Day'), ('Regular Holiday', 'Regular Holiday'), ('Regular Holiday and Rest Day', 'Regular Holiday and Rest Day'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Sick Leave', 'Sick Leave'), ('Paternity Leave', 'Paternity Leave'), ('Leave without pay', 'Leave without pay'), ('Others', 'Others')], default=('Regular Day', 'Regular Day'), max_length=100),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='payment_computation_overtime',
            field=models.CharField(choices=[('Ordinary Days', 'Ordinary Days'), ('Rest Day, Special Day, or Regular Day', 'Rest Day, Special Day, or Regular Day')], default=('Ordinary Days', 'Ordinary Days'), max_length=100),
        ),
    ]
