# Generated by Django 2.2.3 on 2020-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20200528_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
