# Generated by Django 2.2.3 on 2020-05-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_employeesalary_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayroll',
            name='payroll_date',
            field=models.DateField(auto_now=True),
        ),
    ]
