# Generated by Django 2.2.3 on 2020-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20200531_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='deducted_salary_cash_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
