# Generated by Django 2.2.3 on 2020-06-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20200601_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('department', models.CharField(default='None', max_length=150)),
                ('status', models.CharField(default='None', max_length=150)),
                ('no_days', models.IntegerField()),
                ('inclusive_dates', models.CharField(max_length=100)),
                ('reasons', models.CharField(max_length=250)),
                ('classification_of_leave', models.CharField(choices=[('Others', 'Others'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Sick Leave', 'Sick Leave'), ('Paternity Leave', 'Paternity Leave'), ('Leave without pay', 'Leave without pay')], default='Others', max_length=100)),
                ('leave_creadits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('less_this_application', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_as_of_this_date', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ab_personal_fk', to='application.PersonalInfo')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cb_personal_fk', to='application.PersonalInfo')),
                ('employee_leave_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave_fk', to='application.PersonalInfo')),
                ('noted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nb_personal_fk', to='application.PersonalInfo')),
            ],
        ),
    ]
