# Generated by Django 2.2.3 on 2020-06-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_employeeleaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='leave_creadits',
            new_name='leave_credits',
        ),
    ]
