# Generated by Django 2.2.3 on 2020-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20200603_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='checked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='noted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
