# Generated by Django 2.2.3 on 2020-06-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20200603_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
