# Generated by Django 2.2.3 on 2020-06-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_companyinfo_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeItenerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('noted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_itenerary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_itenerary_fk', to='application.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIteneraryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('timeIn', models.CharField(max_length=100)),
                ('timeOut', models.CharField(max_length=100)),
                ('reasons', models.CharField(max_length=250)),
                ('employee_itenerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_itenerary', to='application.EmployeeItenerary')),
            ],
        ),
    ]
