# Generated by Django 2.2.3 on 2020-06-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_employeeitenerary_employeeitenerarydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_fk', to='application.EmployeeItenerary')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_fk', to='application.EmployeeItenerary')),
            ],
        ),
    ]
