# Generated by Django 2.2.3 on 2020-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20200611_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerns',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
