# Generated by Django 2.2.3 on 2020-06-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20200621_0308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotifacations',
        ),
    ]
