# Generated by Django 2.2.3 on 2020-06-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_delete_adminnotifacations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Uploading File', 'Uploading File'), ('Delete Uploaded File', 'Delete Uploaded File'), ('Creating Payroll', 'Creating Payroll'), ('Updating Payroll Settings', 'Updating Payroll Settings'), ('Updating Profile', 'Updating Profile'), ('Updating Password', 'Updating Password'), ('New User Registration', 'New User Registration'), ('Creating Employee Transaction', 'Creating Employee Transaction'), ('Updating Employee Transaction', 'Updating Employee Transaction'), ('Deleting Employee Transaction', 'Deleting Employee Transaction')], default='Uploading File', max_length=150)),
                ('level', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='success', max_length=150)),
                ('public', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_receiver_fk', to='application.PersonalInfo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_sender_fk', to='application.PersonalInfo')),
            ],
        ),
    ]
